name: "action-upload-gofile"

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Upload File
              uses: ./
              id: gofile
              with:
                  token: ${{ secrets.GOFILE_TOKEN }}
                  file: ./example.webp

            - name: Output
              run: |
                  echo "Gofile URL = ${{ steps.gofile.outputs.url }}" 
                  echo "Gofile QR Code = ${{ steps.gofile.outputs.qrcode }}"
